# Generated by Django 5.2.11 on 2026-02-08 22:24

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRiservato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', fernet_fields.fields.EncryptedCharField(help_text='Criptato nel database', max_length=16)),
                ('file_documento', models.FileField(upload_to='docs/%Y/%m/%d/')),
                ('file_hash', models.CharField(editable=False, max_length=64)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('download_effettuati', models.IntegerField(default=0)),
                ('limite_download', models.IntegerField(default=10)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Riservato',
                'verbose_name_plural': 'Documenti Riservati',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('doc_id', models.IntegerField(null=True)),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
