# Generated by Django 5.2.11 on 2026-02-09 01:40

import paz_enc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paz_enc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoriservato',
            name='file_documento',
            field=models.FileField(upload_to=paz_enc.models.secure_rename),
        ),
        migrations.AlterField(
            model_name='documentoriservato',
            name='limite_download',
            field=models.IntegerField(default=5),
        ),
    ]
